from .BertPostProcessor import BertPostProcessor
from .CANTMpostProcessor import CANTMpostProcessor
from .SentRelPostProcessor import SentRelPostProcessor
from .BERTRelAttPostProcessor import BERTRelAttPostProcessor
from .SBDMisInfoPostProcessor import SBDMisInfoPostProcessor
from .SBDSentRelPostProcessor import SBDSentRelPostProcessor
from .AutoModelPostProcessor import AutoModelPostProcessor
from .SBERTNLIPostProcessor import SBERTNLIPostProcessor
